jwt:
  secret: '5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437'
spring:
  application:
    name: Task Manager
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager_db
    username: taskmanager_user
    password: admin12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         format_sql: true
logging:
  level:
    org:
      springframework:
        web: DEBUG









#  use this when running the docker container
#  docker run -e JWT_SECRET="your_secret_value_here" your-image

